// Coherence Fabric -- Apache License 2.0 -- Copyright 2026 Summon Software Labs.
//
// coherence_agent: a participant process holding real memory regions.
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <iostream>
#include <string>
#include <vector>

#include "coherence/agent.hpp"
#include "coherence/transport.hpp"
#include "coherence/version.hpp"

namespace {

void usage() {
  std::fputs(
      "coherence_agent -- Coherence Fabric participant agent\n"
      "\n"
      "usage: coherence_agent --coordinator HOST:PORT [options]\n"
      "\n"
      "  --coordinator HOST:PORT   coordinator endpoint (required)\n"
      "  --name NAME               participant name (required)\n"
      "  --boot HEX32              participant boot identity; a fresh one is generated by default\n"
      "  --node LABEL              node label\n"
      "  --domain NAME             coherence domain name (default 'default')\n"
      "  --object NAME             logical coherence object name (default 'object')\n"
      "  --object-length N         logical extent (required)\n"
      "  --consistency MODEL       strict | release_acquire | snapshot | eventual\n"
      "  --stale-read POLICY       never | bounded | always\n"
      "  --stale-bound N           bound for bounded stale reads\n"
      "  --region SPEC             NAME:MEMORY_DOMAIN:OFFSET:LENGTH[:SEED[:BACKING]]\n"
      "                            BACKING is heap | shared | synthetic\n"
      "  --shared-segment NAME     segment name used by 'shared' backing regions\n"
      "  --create-segment          create rather than attach the shared segment\n"
      "  --stage NAME:LENGTH[:create]  shared staging segment used for real byte movement\n"
      "  --command CMD             append a script command (repeatable)\n"
      "  --script PATH             read script commands from PATH ('-' reads standard input)\n"
      "  --stay                    keep the session open after the script completes\n"
      "  --print-boot              print the boot identity before connecting\n"
      "  --help                    print this help and exit\n",
      stdout);
}

bool next_value(int argc, char** argv, int& index, std::string& out) {
  if (index + 1 >= argc) return false;
  out = argv[++index];
  return true;
}

std::vector<std::string> split(const std::string& text, char separator) {
  std::vector<std::string> parts;
  std::string current;
  for (const char c : text) {
    if (c == separator) {
      parts.push_back(current);
      current.clear();
      continue;
    }
    current.push_back(c);
  }
  parts.push_back(current);
  return parts;
}

coherence::MemoryDomain parse_domain(const std::string& token) {
  const auto parsed = coherence::parse_memory_domain(token);
  return parsed.has_value() ? parsed.value() : coherence::MemoryDomain::Unknown;
}

} // namespace

int main(int argc, char** argv) {
  coherence::AgentOptions options;
  std::string coordinator_endpoint;
  std::string shared_segment;
  bool create_segment = false;
  bool print_boot = false;

  for (int i = 1; i < argc; ++i) {
    const std::string arg = argv[i];
    std::string value;
    if (arg == "--help" || arg == "-h") {
      usage();
      return 0;
    }
    if (arg == "--coordinator" && next_value(argc, argv, i, value)) {
      coordinator_endpoint = value;
      continue;
    }
    if (arg == "--name" && next_value(argc, argv, i, value)) {
      options.client.participant_name = value;
      continue;
    }
    if (arg == "--boot" && next_value(argc, argv, i, value)) {
      if (value.size() != 32) {
        std::fprintf(stderr, "coherence_agent: --boot expects 32 hexadecimal characters\n");
        return 2;
      }
      coherence::UInt128 raw{};
      raw.high = std::strtoull(value.substr(0, 16).c_str(), nullptr, 16);
      raw.low = std::strtoull(value.substr(16, 16).c_str(), nullptr, 16);
      options.client.boot = coherence::ParticipantBootId::from_value(raw);
      continue;
    }
    if (arg == "--node" && next_value(argc, argv, i, value)) {
      options.client.node_label = value;
      continue;
    }
    if (arg == "--domain" && next_value(argc, argv, i, value)) {
      options.domain_name = value;
      continue;
    }
    if (arg == "--object" && next_value(argc, argv, i, value)) {
      options.object_name = value;
      continue;
    }
    if (arg == "--object-length" && next_value(argc, argv, i, value)) {
      options.object_length = std::strtoull(value.c_str(), nullptr, 10);
      continue;
    }
    if (arg == "--consistency" && next_value(argc, argv, i, value)) {
      const auto parsed = coherence::parse_consistency_model(value);
      if (!parsed.has_value()) {
        std::fprintf(stderr, "coherence_agent: unknown consistency model '%s'\n", value.c_str());
        return 2;
      }
      options.consistency = parsed.value();
      continue;
    }
    if (arg == "--stale-read" && next_value(argc, argv, i, value)) {
      const auto parsed = coherence::parse_stale_read_policy(value);
      if (!parsed.has_value()) {
        std::fprintf(stderr, "coherence_agent: unknown stale read policy '%s'\n", value.c_str());
        return 2;
      }
      options.stale_read_policy = parsed.value();
      continue;
    }
    if (arg == "--stale-bound" && next_value(argc, argv, i, value)) {
      options.stale_read_bound = std::strtoull(value.c_str(), nullptr, 10);
      continue;
    }
    if (arg == "--region" && next_value(argc, argv, i, value)) {
      const std::vector<std::string> parts = split(value, ':');
      if (parts.size() < 4) {
        std::fprintf(stderr, "coherence_agent: --region expects NAME:DOMAIN:OFFSET:LENGTH\n");
        return 2;
      }
      coherence::RegionSpec spec;
      spec.name = parts[0];
      spec.memory_domain = parse_domain(parts[1]);
      if (spec.memory_domain == coherence::MemoryDomain::Unknown) {
        std::fprintf(stderr, "coherence_agent: unknown memory domain '%s'\n", parts[1].c_str());
        return 2;
      }
      spec.offset = std::strtoull(parts[2].c_str(), nullptr, 10);
      spec.length = std::strtoull(parts[3].c_str(), nullptr, 10);
      if (parts.size() > 4) spec.seed = std::strtoull(parts[4].c_str(), nullptr, 10);
      if (parts.size() > 5) {
        if (parts[5] == "shared") {
          spec.backing = coherence::adapters::RegionBacking::SharedMapping;
          spec.segment_name = shared_segment;
          spec.create_segment = create_segment;
        } else if (parts[5] == "synthetic") {
          spec.backing = coherence::adapters::RegionBacking::Synthetic;
        } else if (parts[5] == "heap") {
          spec.backing = coherence::adapters::RegionBacking::HostHeap;
        } else {
          std::fprintf(stderr, "coherence_agent: unknown region backing '%s'\n", parts[5].c_str());
          return 2;
        }
      }
      options.regions.push_back(std::move(spec));
      continue;
    }
    if (arg == "--shared-segment" && next_value(argc, argv, i, value)) {
      shared_segment = value;
      for (coherence::RegionSpec& spec : options.regions) {
        if (spec.backing == coherence::adapters::RegionBacking::SharedMapping) {
          spec.segment_name = value;
        }
      }
      continue;
    }
    if (arg == "--create-segment") {
      create_segment = true;
      for (coherence::RegionSpec& spec : options.regions) {
        if (spec.backing == coherence::adapters::RegionBacking::SharedMapping) {
          spec.create_segment = true;
        }
      }
      continue;
    }
    if (arg == "--stage" && next_value(argc, argv, i, value)) {
      const std::vector<std::string> parts = split(value, ':');
      if (parts.size() < 2) {
        std::fprintf(stderr, "coherence_agent: --stage expects NAME:LENGTH[:create]\n");
        return 2;
      }
      options.staging_segment = parts[0];
      options.staging_length = std::strtoull(parts[1].c_str(), nullptr, 10);
      if (parts.size() > 2 && parts[2] == "create") options.staging_create = true;
      continue;
    }
    if (arg == "--command" && next_value(argc, argv, i, value)) {
      options.script.push_back(value);
      continue;
    }
    if (arg == "--script" && next_value(argc, argv, i, value)) {
      std::istream* stream = nullptr;
      std::ifstream file;
      if (value == "-") {
        stream = &std::cin;
      } else {
        file.open(value);
        if (!file.is_open()) {
          std::fprintf(stderr, "coherence_agent: cannot open script '%s'\n", value.c_str());
          return 2;
        }
        stream = &file;
      }
      std::string line;
      while (std::getline(*stream, line)) {
        if (line.empty() || line[0] == '#') continue;
        options.script.push_back(line);
      }
      continue;
    }
    if (arg == "--stay") {
      options.stay_open = true;
      continue;
    }
    if (arg == "--print-boot") {
      print_boot = true;
      continue;
    }
    std::fprintf(stderr, "coherence_agent: unrecognised argument '%s'\n", arg.c_str());
    return 2;
  }

  if (coordinator_endpoint.empty()) {
    std::fprintf(stderr, "coherence_agent: --coordinator is required\n");
    return 2;
  }
  auto endpoint = coherence::parse_endpoint(coordinator_endpoint, 0);
  if (!endpoint.has_value()) {
    std::fprintf(stderr, "coherence_agent: %s\n", endpoint.status().to_string().c_str());
    return 2;
  }
  options.client.host = endpoint.value().first;
  options.client.port = endpoint.value().second;
  if (options.client.boot.is_nil()) {
    options.client.boot = coherence::generate_participant_boot_id();
  }
  if (options.client.boot.is_nil()) {
    std::fprintf(stderr, "coherence_agent: a boot identity could not be generated\n");
    return 1;
  }

  if (print_boot) {
    std::printf("boot=%s\n", options.client.boot.to_string().c_str());
    std::fflush(stdout);
  }

  coherence::Agent agent;
  coherence::Status configured = agent.configure(std::move(options));
  if (!configured.ok()) {
    std::fprintf(stderr, "coherence_agent: %s\n", configured.to_string().c_str());
    return 1;
  }
  coherence::Status joined = agent.join();
  if (!joined.ok()) {
    std::fprintf(stderr, "coherence_agent: %s\n", joined.to_string().c_str());
    return 1;
  }
  std::string region_summary;
  for (const coherence::RegionSpec& spec : agent.options().regions) {
    const coherence::RegionId id = agent.region_id(spec.name);
    if (!region_summary.empty()) region_summary.push_back(',');
    region_summary += spec.name + ":" + id.to_string();
  }
  std::printf("joined=1 participant=%s object=%s regions=%s\n",
              agent.client().participant().to_string().c_str(),
              agent.object().to_string().c_str(), region_summary.c_str());
  std::fflush(stdout);

  std::vector<std::string> sink;
  coherence::Status executed = agent.run_script(sink);
  for (const std::string& entry : sink) {
    std::printf("%s\n", entry.c_str());
  }
  std::fflush(stdout);
  if (!executed.ok()) {
    std::fprintf(stderr, "coherence_agent: %s\n", executed.to_string().c_str());
    (void)agent.leave();
    return 1;
  }

  if (agent.options().stay_open) {
    // Hold the session open and keep serving commands read from standard input
    // until the harness closes it. The multiprocess proof kills this process at
    // a chosen lifecycle point, which is exactly the behaviour under test, and
    // the harness never has to guess how long to wait.
    std::printf("holding=1\n");
    std::fflush(stdout);
    std::string command;
    while (std::getline(std::cin, command)) {
      if (command.empty() || command[0] == '#') continue;
      std::vector<std::string> more;
      coherence::Status step = agent.execute(command, more);
      for (const std::string& entry : more) std::printf("%s\n", entry.c_str());
      std::printf("command_status=%s\n",
                  std::string(coherence::status_code_name(step.code())).c_str());
      std::fflush(stdout);
    }
  }

  (void)agent.leave();
  std::printf("left=1\n");
  std::fflush(stdout);
  return 0;
}
